env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: "0.0.0.0:8082"
  timeout: 10s
  idle_timeout: 60s
  user: "admin"
  password: "admin"
clients:
  sso:
    address: "localhost:50051"
    timeout: 2s
    retries_count: 3
app_secret: "dev-secret"
